apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: docker.pkg.github.com/navikt/sosialhjelp-modia-api/sosialhjelp-modia-api-2:{{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 4
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: {{application_vault_path}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: {{virksomhetssertifikat_vault_path}}
        mountPath: /var/run/secrets/nais.io/virksomhetssertifikat
      - kvPath: {{serviceuser_vault_path}}
        mountPath: /secrets/serviceuser/srvsosialhjelp-mod
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
{{#each ingress}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
