apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
{{#if accessPoliciesForGcpEnabled}}
  accessPolicy:
    outbound:
      external:
        - host: "oidc-ver2.difi.no"
        - host: "register.geonorge.no"
      rules:
        - application: sosialhjelp-mock-alt-api
  filesFrom:
    - secret: virksomhetssertifikat
{{/if}}
  vault:
    enabled: {{vaultEnabled}}
{{#if vaultEnabled}}
    paths:
{{#each secretKvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
