apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
  vault:
    enabled: {{vaultEnabled}}
{{#if vaultEnabled}}
    paths:
      - kvPath: {{application_vault_path}}
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: {{virksomhetssertifikat_vault_path}}
        mountPath: /var/run/secrets/nais.io/virksomhetssertifikat
{{#each secretKvPaths}}
      - mountPath: {{@key}}
        kvPath: {{this}}
{{/each}}
{{/if}}
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
