apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "82efbcf9-7a99-4c60-9242-79c439ca3cdc" # 0000-GA-Modia_Sosialhjelp_NKS
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    cpuThresholdPercentage: 70
    min: 1
    max: 2
  valkey:
    - instance: modia-api
      access: readwrite
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  accessPolicy:
    outbound:
      external:
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
        - host: api.fiks.ks.no
        - host: pdl-api.prod-fss-pub.nais.io
      rules:
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: saas-proxy
          namespace: teamcrm
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - secret: fiks-integrasjon-secret
    - secret: sosialhjelp-modia-api-unleash-api-token
  ingresses:
    - "https://sosialhjelp-modia-api-gcp.intern.nav.no/sosialhjelp/modia-api"
    - "https://sosialhjelp-modia-api-gcp.prod-fss-pub.nais.io"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "gcp,log-kibana"
    - name: AZURE_GRAPH_API_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: VEILEDER_GRUPPE_ID
      value: "82efbcf9-7a99-4c60-9242-79c439ca3cdc"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.ks.no"
    - name: NORG_ENDPOINT_URL
      value: "http://norg2.org/norg2/api/v1"
    - name: NORG_OPPSLAG_URL
      value: "https://norg2-frontend.ekstern.nav.no/#/startsok?enhetNr="
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "http://skjermede-personer-pip.nom"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "api://prod-gcp.nom.skjermede-personer-pip/.default"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "60"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-modia-api"
    - name: UNLEASH_ENV
      value: "prod-gcp"
    - name: SWAGGER_ENABLED
      value: "true"
    - name: MODIA_BASEURL
      value: "https://sosialhjelp-modia.intern.nav.no/sosialhjelp/modia"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "https://maskinporten.no/.well-known/oauth-authorization-server"
