apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "82efbcf9-7a99-4c60-9242-79c439ca3cdc" # 0000-GA-Modia_Sosialhjelp_NKS
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    cpuThresholdPercentage: 70
    min: 2
    max: 4
  webproxy: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  envFrom:
    - secret: redis-password-modia-api
    - secret: fiks-integrasjon-secret
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-modia-oidc-auth-proxy
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
  ingresses:
    - "https://sosialhjelp-modia-api.intern.nav.no/sosialhjelp/modia-api"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 25m
      memory: 512Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "prod-fss,log-kibana,log-audit"
    - name: AZURE_GRAPH_API_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: VEILEDER_GRUPPE_ID
      value: "82efbcf9-7a99-4c60-9242-79c439ca3cdc"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.ks.no"
    - name: NORG_ENDPOINT_URL
      value: "https://norg2.intern.nav.no/norg2/api/v1"
    - name: NORG_OPPSLAG_URL
      value: "https://norg2-frontend.intern.nav.no/#/startsok?enhetNr="
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.intern.nav.no/graphql"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "https://skjermede-personer-pip.intern.nav.no"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "api://prod-gcp.nom.skjermede-personer-pip/.default"
    - name: REDIS_HOST
      value: "sosialhjelp-modia-api-redis.teamdigisos.svc.nais.local"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "180"
    - name: DOKUMENT_CACHE_TIME_TO_LIVE_SECONDS
      value: "360"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api"
    - name: UNLEASH_INSTANCE_ID
      value: "prod-fss"
    - name: SWAGGER_ENABLED
      value: "false"
    - name: MODIA_BASEURL
      value: "https://sosialhjelp-modia.intern.nav.no/sosialhjelp/modia"
