mock-alt-api-host: ${MOCK_ALT_API_HOST:127.0.0.1}
mock-alt-api-wellknown-queryparam: ${MOCK_ALT_API_WELLKNOWN_QUERYPARAM:}

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${METADATA_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/azuread${mock-alt-api-wellknown-queryparam}}
    accepted_audience: someaudience
    cookie_name: localhost-idtoken

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}

client:
  abac_pdp_endpoint_url: ${ABAC_PDP_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/abac/application/authorize}
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks}
  fiks_integrasjonid: ${INTEGRASJONSID_FIKS:id}
  fiks_integrasjonpassord: ${INTEGRASJONPASSORD_FIKS:pwd}
  norg_endpoint_url: ${NORG_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/norg_endpoint_url}
  norg_oppslag_url: ${NORG_OPPSLAG_URL:https://norg2-frontend.nais.adeo.no/#/startsok?enhetNr=}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/pdl_endpoint_url}
  sts_token_endpoint_url: ${STS_TOKEN_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/sts_token_endpoint_url/token}
  bergen_kommunenummer: ${BERGEN_KOMMUNENUMMER:0301}
  stavanger_kommunenummer: ${STAVANGER_KOMMUNENUMMER:1103}
  azure_token_endpoint_url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azuretoken/selvbetjening}
  skjermede_personer_scope: ${SKJERMEDE_PERSONER_SCOPE:dummyScope}
  skjermede_personer_endpoint_url: ${SKJERMEDE_PERSONER_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/skjermede-personer}
  unleash_url: ${UNLEASH_API_URL:https://unleash.nais.io/api}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID:local}

#Maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA

loginurl: ${LOGINURL:http://localhost:8383/sosialhjelp/modia-api/local/cookie}
