spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: 1313
    password: ${REDIS_PASSWORD:foobar}

modia:
  cache:
    redis_mocked: true
    time_to_live_seconds: 2

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

client:
  abac_pdp_endpoint_url: abac_pdp_endpoint_url
  fiks_digisos_endpoint_url: digisosapiurl
  fiks_integrasjonid: integrasjonid
  fiks_integrasjonid_kommune: integrasjonidkommune
  fiks_integrasjonpassord: integrasjonpw
  fiks_integrasjonpassord_kommune: integrasjonpwkommune
  norg_endpoint_url: norgurl
  pdl_endpoint_url: pdlurl
  sts_token_endpoint_url: stsurl

no.nav.sosialhjelp.idporten:
  token_url: tokenurl
  client_id: clientid
  scope: scope
  config_url: configurl
  truststore_type: truststoretype
  truststore_filepath: truststorefilepath

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

loginurl: ${LOGINURL:http://localhost:8383/sosialhjelp/modia-api/local/cookie}