spring:
  redis:
    host: localhost
    port: 6379
    password:

management:
  endpoints:
    web:
      exposure:
        exclude: '*'

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: http://localhost:${mock-oauth2-server.port}/azuread/.well-known/openid-configuration
    accepted_audience: someaudience
    cookie_name: localhost-idtoken

springdoc:
  api-docs:
    enabled: true

client:
  abac_pdp_endpoint_url: abac_pdp_endpoint_url
  fiks_digisos_endpoint_url: digisosapiurl
  fiks_integrasjonid: integrasjonid
  fiks_integrasjonid_kommune: integrasjonidkommune
  fiks_integrasjonpassord: integrasjonpw
  fiks_integrasjonpassord_kommune: integrasjonpwkommune
  norg_endpoint_url: norgurl
  norg_oppslag_url: norgurl2
  pdl_endpoint_url: pdlurl
  sts_token_endpoint_url: stsurl
  unleash_url: unleashurl
  unleash_instance_id: local

no.nav.sosialhjelp.idporten:
  token_url: tokenurl
  client_id: clientid
  scope: scope
  config_url: configurl

loginurl: ${LOGINURL:http://localhost:8383/sosialhjelp/modia-api/local/cookie}
