mock-alt-api-host: ${MOCK_ALT_API_HOST:127.0.0.1}
mock-alt-api-wellknown-queryparam: ${MOCK_ALT_API_WELLKNOWN_QUERYPARAM:}

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${METADATA_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/azuread${mock-alt-api-wellknown-queryparam}}
    accepted_audience: someaudience
    cookie_name: localhost-idtoken

springdoc:
  api-docs:
    enabled: true

client:
  fiks_digisos_endpoint_url: ${FIKS_DIGISOS_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/fiks}
  fiks_integrasjonid: id
  fiks_integrasjonpassord: pwd
  norg_endpoint_url: ${NORG_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/norg_endpoint_url}
  norg_oppslag_url: ${NORG_OPPSLAG_URL:https://norg2-frontend.ekstern.dev.nav.no/#/startsok?enhetNr=}
  pdl_endpoint_url: ${PDL_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/pdl_endpoint_url}
  pdl_scope: dummyScope
  veileder_gruppe_id: 0000-MOCK-sosialhjelp-modia-veileder
  azure_token_endpoint_url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azuretoken/selvbetjening}
  azure_client_secret: secret
  azuredings_jwt_audience: dummyAudience
  azuredings_url: ${AZURE_APP_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azure-well-known/selvbetjening}
  azuredings_jwt_client_id: localhost:teamdigisos:sosialhjelp-dialog-api
  azuredings_private_jwk: generateRSA
  azure_graph_url: ${AZURE_GRAPH_API_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/azuread/graph}
  skjermede_personer_scope: dummyScope
  skjermede_personer_endpoint_url: ${SKJERMEDE_PERSONER_ENDPOINT_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/skjermede-personer}
  unleash_instance_id: ${UNLEASH_INSTANCE_ID:local}
  unleash_env: ${UNLEASH_ENV:mock}
  unleash_server_api_url: ${UNLEASH_SERVER_API_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/internal/unleash}
  unleash_server_api_token: ${UNLEASH_SERVER_API_TOKEN:token}

modia_baseurl: ${MODIA_BASEURL:https://digisos.ekstern.dev.nav.no/sosialhjelp/modia}

#Maskinporten
maskinporten_clientid: maskinporten_clientid
maskinporten_scopes: scopes
maskinporten_well_known_url: ${MASKINPORTEN_WELL_KNOWN_URL:http://${mock-alt-api-host}:8989/sosialhjelp/mock-alt-api/well-known/maskinporten${mock-alt-api-wellknown-queryparam}}
maskinporten_client_jwk: generateRSA

loginurl: ${LOGINURL:http://localhost:8383/sosialhjelp/modia-api/local/cookie}
