apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{applicationName}}
  namespace: {{namespace}}
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  azure:
    application:
      enabled: {{azureEnabled}}
{{#if dev}}
      tenant: trygdeetaten.no
{{/if}}
{{#if wonderwallEnabled}}
    sidecar:
      enabled: true
      autoLogin: false
{{/if}}
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: {{prometheusEnabled}}
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
  webproxy: {{webProxyEnabled}}
{{#if maskinportenEnabled}}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
{{/if}}
{{#unless isLabsGcp}}
  envFrom:
{{#each envsecret}}
    - secret: "{{this}}"
{{/each}}
{{/unless}}
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-modia-oidc-auth-proxy
    outbound:
      external:
        - host: "oidc-ver2.difi.no"
        - host: "register.geonorge.no"
        - host: "login.microsoftonline.com"
        - host: "unleash.nais.io"
      rules:
        - application: sosialhjelp-mock-alt-api-mock
        - application: sosialhjelp-modia-api-redis
  ingresses:
{{#each ingress}}
    - "{{this}}"
{{/each}}
  resources:
    limits:
      cpu: {{cpuLimit}}
      memory: {{memoryLimit}}
    requests:
      cpu: {{cpuRequest}}
      memory: {{memoryRequest}}
  env:
{{#each env}}
    - name: {{@key}}
      value: "{{this}}"
{{/each}}
