apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  azure:
    sidecar:
      autoLogin: true
      autoLoginIgnorePaths:
        - /sosialhjelp/modia-api/api/**
        - /api/**
      enabled: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7357bc5c-8389-435d-8311-46452d356a83" # 0000-GA-Modia_Sosialhjelp_NKS
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    cpuThresholdPercentage: 70
    min: 1
    max: 2
  valkey:
    - instance: modia-api
      access: readwrite
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  accessPolicy:
    outbound:
      external:
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
        - host: api.fiks.test.ks.no
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: skjermede-personer-pip
          namespace: nom
        - application: norg2
          namespace: org

  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 25m
      memory: 512Mi
  envFrom:
    - secret: fiks-integrasjon-secret
    - secret: sosialhjelp-modia-api-unleash-api-token
  ingresses:
    - "https://sosialhjelp-modia-api.ansatt.dev.nav.no/sosialhjelp/modia-api"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "gcp,log-kibana,dev"
    - name: AZURE_GRAPH_API_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: VEILEDER_GRUPPE_ID
      value: "7357bc5c-8389-435d-8311-46452d356a83"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.test.ks.no"
    - name: NORG_ENDPOINT_URL
      value: "http://norg2.org/norg2/api/v1"
    - name: NORG_OPPSLAG_URL
      value: "https://norg2-frontend.ekstern.dev.nav.no/#/startsok?enhetNr="
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "http://skjermede-personer-pip.nom"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "api://dev-gcp.nom.skjermede-personer-pip/.default"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "60"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-modia-api"
    - name: UNLEASH_ENV
      value: "dev-gcp"
    - name: SWAGGER_ENABLED
      value: "true"
    - name: MODIA_BASEURL
      value: "https://sosialhjelp-modia.intern.dev.nav.no/sosialhjelp/modia"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "https://test.maskinporten.no/.well-known/oauth-authorization-server"
