apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api-dev
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "7357bc5c-8389-435d-8311-46452d356a83" # 0000-GA-Modia_Sosialhjelp_NKS
    sidecar:
      enabled: true
      autoLogin: false
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    cpuThresholdPercentage: 70
    min: 1
    max: 2
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "ks:fiks"
  envFrom:
    - secret: redis-password-modia-api
    - secret: fiks-integrasjon-secret
    - secret: sosialhjelp-modia-api-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: oidc-ver2.difi.no
        - host: register.geonorge.no
        - host: login.microsoftonline.com
        - host: unleash.nais.io
        - host: api.fiks.test.ks.no
        - host: graph.microsoft.com
        - host: norg2.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: skjermede-personer-pip.dev.intern.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
      rules:
        - application: sosialhjelp-modia-api-redis
  ingresses:
    - "https://sosialhjelp-modia-dev.dev.nav.no/sosialhjelp/modia-api"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 512Mi
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "dev,log-console,log-audit"
    - name: AZURE_GRAPH_API_URL
      value: "https://graph.microsoft.com/v1.0"
    - name: VEILEDER_GRUPPE_ID
      value: "7357bc5c-8389-435d-8311-46452d356a83"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "https://api.fiks.test.ks.no"
    - name: NORG_ENDPOINT_URL
      value: "https://norg2.dev-fss-pub.nais.io/norg2/api/v1"
    - name: NORG_OPPSLAG_URL
      value: "https://norg2-frontend.dev.intern.nav.no/#/startsok?enhetNr="
    - name: PDL_ENDPOINT_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "https://skjermede-personer-pip.dev.intern.nav.no"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "api://dev-gcp.nom.skjermede-personer-pip/.default"
    - name: REDIS_HOST
      value: "sosialhjelp-modia-api-redis.teamdigisos.svc.cluster.local"
    - name: CACHE_TIME_TO_LIVE_SECONDS
      value: "60"
    - name: UNLEASH_INSTANCE_ID
      value: "sosialhjelp-modia-api"
    - name: UNLEASH_ENV
      value: "dev"
    - name: SWAGGER_ENABLED
      value: "true"
    - name: MODIA_BASEURL
      value: "https://sosialhjelp-modia-dev.dev.nav.no/sosialhjelp/modia"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "https://ver2.maskinporten.no/.well-known/oauth-authorization-server"
