apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-modia-api-mock
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8383
  liveness:
    path: /sosialhjelp/modia-api/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 10
  readiness:
    path: /sosialhjelp/modia-api/internal/isReady
    initialDelay: 60
    timeout: 1
  prometheus:
    enabled: true
    path: /sosialhjelp/modia-api/internal/prometheus
  replicas:
    cpuThresholdPercentage: 70
    min: 1
    max: 2
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  accessPolicy:
    outbound:
      external:
        - host: "unleash.nais.io"
        - host: digisos.ekstern.dev.nav.no
        - host: teamdigisos-unleash-api.nav.cloud.nais.io
        - host: register.geonorge.no
      rules:
        - application: sosialhjelp-mock-alt-api-mock
  ingresses:
    - "https://digisos.ekstern.dev.nav.no/sosialhjelp/modia-api"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 512Mi
  envFrom:
    - secret: sosialhjelp-modia-api-unleash-api-token
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "mock-alt,log-kibana,no-redis"
    - name: METADATA_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/azuread"
    - name: AZURE_APP_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/azure-well-known/selvbetjening"
    - name: FIKS_DIGISOS_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/fiks"
    - name: NORG_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/norg_endpoint_url"
    - name: NORG_OPPSLAG_URL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/modia"
    - name: PDL_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/pdl_endpoint_url"
    - name: SKJERMEDE_PERSONER_ENDPOINT_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/skjermede-personer"
    - name: MASKINPORTEN_WELL_KNOWN_URL
      value: "http://sosialhjelp-mock-alt-api-mock/sosialhjelp/mock-alt-api/well-known/maskinporten"
    - name: MODIA_BASEURL
      value: "https://digisos.ekstern.dev.nav.no/sosialhjelp/modia"
