name: Auto-deploy redis dev
on:
  push: # Deploys automatically to dev-fss and dev-gcp if there is a change in any redis files.
    paths:
      - "nais/redis-config.yml"
      - "nais/redisexporter.yml"
      - ".github/workflows/autodeploy_dev_redis.yml"
    branches-ignore:
      - 'master'
    tags-ignore:
      - "**" # Don't build any tags

env:
  CI: true

jobs:
  deploy-dev-fss:
    name: Auto-deploy redis to dev-fss
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3
      - name: Deploye redis til dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-fss
          TEAM: teamdigisos
          RESOURCE: "nais/redis-config.yml,nais/redisexporter.yml"

  deploy-dev-gcp:
    name: Auto-deploy redis to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3
      - name: Deploye redis til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLUSTER: dev-gcp
          TEAM: teamdigisos
          RESOURCE: "nais/redis-config.yml,nais/redisexporter.yml"
