name: 'Auto-deploy redis dev'
on:
  push: # Deploys automatically to dev-fss and dev-gcp if there is a change in any redis files.
    paths:
      - "nais/redis-config.yml"
      - "nais/redisexporter.yml"
      - ".github/workflows/autodeploy_dev_redis.yml"
    branches-ignore:
      - 'main'
    tags-ignore:
      - "**" # Don't build any tags

jobs:
  deploy-redis:
    name: 'Deploy Redis to Dev'
    permissions:
      id-token: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_redis.yml@v11
    secrets: inherit
    with:
      to-dev-fss: true
