name: 'Auto-deploy redis prod-fss'
on:
  push: # Deploys automatically to prod-fss if there is a change in any redis files.
    paths:
      - "nais/redis-config.yml"
      - "nais/redisexporter.yml"
      - ".github/workflows/autodeploy_prod_redis.yml"
    branches:
      - 'main'
    tags-ignore:
      - "**" # Don't build any tags

jobs:
  deploy-redis:
    name: 'Deploy Redis to Dev'
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_redis.yml@v8
    secrets: inherit
    with:
      to-prod-fss: true
