name: Deploy til dev
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'dev-fss'
        type: choice
        options:
          - 'dev-fss'
          - 'dev'
          - 'mock'

jobs:
  deploy:
    name: Deploy to dev - ${{ github.event.inputs.config-file-name }}
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v3
      - name: Create artifact version
        id: artifact-version
        uses: navikt/sosialhjelp-ci/actions/create-artifact-version@v2
      - name: Sett env variabler
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_IMAGE }}:${{ steps.artifact-version.outputs.version }}" >> $GITHUB_ENV
      - name: Sett cluster basert på config-file
        run: |
          if [[ ${{ github.event.inputs.config-file-name }} = 'dev-fss' ]]; then
            echo "CLUSTER_NAME=dev-fss" >> $GITHUB_ENV
          else
            echo "CLUSTER_NAME=dev-gcp" >> $GITHUB_ENV
          fi
          echo "Deployer til ${{ env.CLUSTER_NAME }}"
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/dev/${{ github.event.inputs.config-file-name }}.yaml
          CLUSTER: ${{ env.CLUSTER_NAME }}
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.DOCKER_TAG }}
