name: Deploy Dev
on:
  repository_dispatch:
    types: [deploy_miljo_tag]

jobs:
  deploy:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    if: github.event.action == 'deploy_miljo_tag'
    steps:
      - name: Sett env variabler
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d/ -f2)-2
          echo ::set-env name=IMAGE::$(echo "docker.pkg.github.com/${{ github.repository }}/$PROJECT_NAME":${{ github.event.client_payload.TAG }})

      - name: checkout $TAG
        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.event.client_payload.TAG }}
      - run: |
          MASTER_HEAD_COMMIT=$(git rev-parse HEAD)
          TAG=${{ github.event.client_payload.TAG }}

          git checkout ${TAG}

          TAG_COMMIT=$(git rev-parse HEAD)
          MERGE_BASE=$(git merge-base $MASTER_HEAD_COMMIT $TAG_COMMIT)

          if [[ $MERGE_BASE != $TAG_COMMIT ]]; then
            echo "${TAG} is not on master branch" 1>&2
            exit 1
          fi

      - name: Deploy til dev-fss
        if: success()
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais.yaml
          CLUSTER: dev-fss
          VARS: nais/dev/${{ github.event.client_payload.MILJO }}.json
          REF: ${{ github.event.client_payload.TAG }}
          PRINT_PAYLOAD: true
