name: Deploy til dev
on:
  workflow_dispatch:
    inputs:
      config-file-name:
        description: 'Config-fil som skal deployes'
        required: true
        default: 'dev-fss'
        type: choice
        options:
          - 'dev-fss'
          - 'dev'
          - 'mock'

jobs:
  set-cluster:
    name: 'Sett cluster basert på config-file'
    runs-on: ubuntu-latest
    outputs:
      cluster-name: ${{ steps.set-cluster-name.outputs.cluster-name }}
    steps:
      - name: Sett cluster basert på config-file
        id: set-cluster-name
        run: |
          if [[ ${{ github.event.inputs.config-file-name }} = 'dev-fss' ]]; then
            echo "cluster-name=dev-fss" >> $GITHUB_OUTPUT
          else
            echo "cluster-name=dev-gcp" >> $GITHUB_OUTPUT
          fi
          echo "Deployer til ${cluster-name}"

  deploy-to-dev:
    name: 'Deploy to dev'
    needs: set-cluster
    permissions:
      packages: write
      contents: write
    uses: navikt/sosialhjelp-ci/.github/workflows/deploy_app.yml@v2
    with:
      cluster-name: ${{ needs.set-cluster.outputs.cluster-name }}
      resource-name: ${{ inputs.config-file-name }}
    secrets: inherit
